# Generated by Django 3.0.5 on 2020-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=3)),
                ('source_url', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
