# Generated by Django 3.0.7 on 2025-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='The title of the news article')),
                ('summary', models.TextField(help_text='A brief summary of the news article')),
                ('source', models.CharField(help_text='The news source name', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('np', 'Nepali')], default='en', help_text='Language of the article', max_length=3)),
                ('source_url', models.URLField(help_text='URL to the original article', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text="URL to the article's featured image", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
